version: '3.9'
services:
  fitness-service:
    image: fitness-service:latest
    container_name: fitness-service
    hostname: local
    env_file:
      - otel.env
      - service.env
    expose:
      - "10001"
    ports:
      - "10001:10000"
    networks:
      - app-bridge-network
      - monitoring-bridge-network
    deploy:
      resources:
        limits:
          memory: 1G

networks:
  app-bridge-network:
    name: app-bridge
    external: true
  monitoring-bridge-network:
    name: monitoring-bridge
    external: true